[package]
name = "app"
version = "0.1.0"
description = "Device Manager for LG webOS"
authors = ["Ningyuan Li"]
license = "Apache-2.0"
repository = "https://github.com/webosbrew/dev-manager-desktop"
default-run = "app"
edition = "2021"
rust-version = "1.59"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.2.1", features = [] }

[dependencies]
tauri = { version = "1.2.4", features = ["clipboard-all", "dialog-all", "path-all", "protocol-all", "shell-open"] }
tauri-plugin-single-instance = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "dev" }
tauri-plugin-window-state = "0.1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_repr = "0.1.10"
log = "0.4.17"
env_logger = "0.10.0"
rand = "0.8.5"
vt100 = "0.15.2"
russh = { version = "0.36.1", features = ["openssl"] }
russh-keys = { version = "0.24.1", features = ["openssl"] }
openssl = { version = "0.10.45", features = ["vendored"] }
tokio = "1.25.0"
uuid = { version = "1.2.2", features = ["v1"] }
reqwest = { version = "0.11.14", features = ["json"] }
async-trait = "0.1.64"
sha2 = "0.10.6"
hex = "0.4.3"
file-mode = "0.1.2"
posix-errors = "1.2.1"
dialog = "0.3.0"
tiny_http = "0.12.0"
path-slash = "0.2.1"
ssh2 = { version = "0.9.4", features = ["openssl-on-win32"] }
httparse = "1.8.0"
crossbeam-channel = "0.5.7"
r2d2 = "0.8.10"
unix_mode = "0.1.3"

[features]
# by default Tauri runs in production mode
# when `tauri dev` runs it is executed with `cargo run --no-default-features` if `devPath` is an URL
default = ["custom-protocol"]
# this feature is used for production builds where `devPath` points to the filesystem
# DO NOT remove this
custom-protocol = ["tauri/custom-protocol"]
