[workspace]
resolver = "2"
members = [
  "src-tauri"
]

[patch.crates-io]
cc = { git = "https://github.com/mariotaku/cc-rs.git", rev = "01a3414" }
r2d2 = { git = "https://github.com/mariotaku/r2d2.git", rev = "aaa2a2b" }
